<?php

namespace DoctrineProxies\__CG__\ApiSkeletons\Laravel\Doctrine\ApiKey\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ApiKey extends \ApiSkeletons\Laravel\Doctrine\ApiKey\Entity\ApiKey implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'accessEvents' => [parent::class, 'accessEvents', null],
        "\0".parent::class."\0".'adminEvents' => [parent::class, 'adminEvents', null],
        "\0".parent::class."\0".'api_key' => [parent::class, 'api_key', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'scopes' => [parent::class, 'scopes', null],
        "\0".parent::class."\0".'status_at' => [parent::class, 'status_at', null],
        'accessEvents' => [parent::class, 'accessEvents', null],
        'adminEvents' => [parent::class, 'adminEvents', null],
        'api_key' => [parent::class, 'api_key', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'is_active' => [parent::class, 'is_active', null],
        'name' => [parent::class, 'name', null],
        'scopes' => [parent::class, 'scopes', null],
        'status_at' => [parent::class, 'status_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
